#!/bin/bash
set -e

if [ "$1" = "--dev" ]; then
    IMAGE=dmp1ce/joinmarket:dev
    PARAMS="${*:2}"
else
    IMAGE=dmp1ce/joinmarket
    PARAMS="$*"
fi

_USERNAME=$(logname)
_HOME=$(eval echo ~"$_USERNAME")
_UID=$(id -u "$_USERNAME")
_GID=$(id -g "$_USERNAME")

# Setup Docker command
if docker info &>/dev/null; then
    DOCKER_CMD=(docker)
else
    DOCKER_CMD=(sudo docker)
fi

if ! "${DOCKER_CMD[@]}" info > /dev/null 2>&1; then
    echo "Failed to run 'docker info'. Please make sure you have access to run docker."
else
    "${DOCKER_CMD[@]}" run --rm -it -e UID="$_UID" -e GID="$_GID" -v "$_HOME/.joinmarket":/home/joinmarket/.joinmarket "$IMAGE" "$PARAMS"
fi
